/**
 * Build script to inject environment variables into client-side code
 * Run this before deploying to inject safe public variables
 */

const fs = require('fs');
const path = require('path');

// Read environment variables (NO hardcoded defaults to prevent secrets leakage)
const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_UPLOAD_PRESET = process.env.CLOUDINARY_UPLOAD_PRESET;

// Validate required environment variables
if (!CLOUDINARY_CLOUD_NAME || !CLOUDINARY_UPLOAD_PRESET) {
  console.error('❌ ERROR: Missing required environment variables for build');
  console.error('Required variables:');
  console.error('  - CLOUDINARY_CLOUD_NAME:', CLOUDINARY_CLOUD_NAME ? '✓' : '✗ MISSING');
  console.error('  - CLOUDINARY_UPLOAD_PRESET:', CLOUDINARY_UPLOAD_PRESET ? '✓' : '✗ MISSING');
  console.error('\nSet these in Netlify: Site settings → Environment variables');
  process.exit(1);
}

// Create env-config.js file
const envConfig = `
// Auto-generated environment configuration
// DO NOT EDIT THIS FILE MANUALLY - it's generated at build time
window.ENV = {
  CLOUDINARY_CLOUD_NAME: '${CLOUDINARY_CLOUD_NAME}',
  CLOUDINARY_UPLOAD_PRESET: '${CLOUDINARY_UPLOAD_PRESET}'
};
`;

// Write to public directory
fs.writeFileSync(
  path.join(__dirname, 'env-config.js'),
  envConfig.trim()
);

console.log('✅ Environment configuration generated successfully');
